### ISSUE TITLE
NHS Test Results Unsupported

### ISSUE THREAD

**Issue by DMBryant** [nhsx/covid-19-app-ios-ag-public#7]
"If your test took place in a Public Health England lab or NHS hospital, or as part of national surveillance testing conducted by the Office for National Statistics, test results cannot currently be linked with the app whether they’re positive or negative." - @NHSCOVID19app on Twitter. 

This is supposed to be an NHS app - it should work with the NHS test results at the very least!

**Comment by ataraxia89** [comment]
Does this also need to be reported on the Android app?

**Comment by DMBryant** [comment]
Yes - and it should probably be on the server component as that is the part that would need to interface with the NHS system.

**Comment by ataraxia89** [comment]
> Yes - and it should probably be on the server component as that is the part that would need to interface with the NHS system.

I have created an issue for the Android app here >> https://github.com/nhsx/covid-19-app-android-ag-public/issues/11

I haven't fully gone through the source code for both apps yet so haven't seen where the responsibility lies for sending test result references to the central server. If this is solely in the shared code then it should be raised as an issue there and the individual app issues should be closed to prevent duplication.

**Comment by DMBryant** [comment]
It's probably more of a project level issue as the backend systems would need to be linked up which would require updates on both sides.

**Comment by ataraxia89** [comment]
I hadn't noticed this has already been reported on Android 🤦‍♂️ so I've closed my issue. The original report is here >> https://github.com/nhsx/covid-19-app-android-ag-public/issues/9

**Comment by ataraxia89** [comment]
Getting information on this is proving extremely difficult because of so many people just stating that NHS results can't be entered without backing it up with a reason, proof or error messages.

It seems as though when an NHS (and presumably ONS) test result comes back it does not have a reference code/number, therefore there is nothing that can be entered into the app.

It suggests that the only test results that can be entered into the app are those that have been booked *via* the app, suggesting there is a reference number that the app issues which is then linked to the test result reference that the testing stations issue. Again, I can't be sure because I haven't been through this process myself and getting hard evidence or sensible answers from people is proving difficult.

If it is as above, then the NHS and ONS issued tests should be registered in the same way. There is obviously a central test booking system in place which uses reference numbers to allocate test results to app users, this same system should be put in place at the point of testing for NHS patients. When the patient takes the test, staff should ask if the patient has the app installed and obtain a test booking reference from the app, this can then be processed in the same way as app-booked tests at the testing centres. For those that don't have the app or are unable to install it due to restrictions, then the current system (without reference numbers) should be used.

**Comment by ataraxia89** [comment]
There is this comment on the help pages for the app:

"If your test took place in a Public Health England lab or NHS hospital, or as part of national surveillance testing conducted by the Office for National Statistics, test results cannot currently be linked with the app whether they’re positive or negative. We are working to make this available as soon as possible."

So it is in the works, but no estimated date given. The above statement is on this page >> https://faq.covid19.nhs.uk/article/KA-01307/en-us?parentid=CAT-01037&rootid=CAT-01032

**Comment by ataraxia89** [comment]
Apparently this has now been resolved, seemingly no update needed for the apps, contact tracers are now issuing codes to people who've been tested at NHS hospitals and Public Health England labs >> https://news.sky.com/story/coronavirus-third-of-tests-in-england-not-linked-to-new-nhs-app-developers-suggest-12082178

If this is true then these issues can be closed and there is no update needed for the apps.

**Comment by DMBryant** [comment]
Excellent news and a VERY swift turnaround!

**Comment by ataraxia89** [comment]
@DMBryant can you close this issue?

**Comment by DMBryant** [comment]
Yep :-)
